export const CITIES = [
  { city: 'New York', state: 'NY', country: 'United States', region: 'americas' },
  { city: 'Los Angeles', state: 'CA', country: 'United States', region: 'americas' },
  { city: 'Chicago', state: 'IL', country: 'United States', region: 'americas' },
  { city: 'Houston', state: 'TX', country: 'United States', region: 'americas' },
  { city: 'Phoenix', state: 'AZ', country: 'United States', region: 'americas' },
  { city: 'Philadelphia', state: 'PA', country: 'United States', region: 'americas' },
  { city: 'San Antonio', state: 'TX', country: 'United States', region: 'americas' },
  { city: 'San Diego', state: 'CA', country: 'United States', region: 'americas' },
  { city: 'Dallas', state: 'TX', country: 'United States', region: 'americas' },
  { city: 'Austin', state: 'TX', country: 'United States', region: 'americas' },
  { city: 'San Francisco', state: 'CA', country: 'United States', region: 'americas' },
  { city: 'Seattle', state: 'WA', country: 'United States', region: 'americas' },
  { city: 'Denver', state: 'CO', country: 'United States', region: 'americas' },
  { city: 'Boston', state: 'MA', country: 'United States', region: 'americas' },
  { city: 'Miami', state: 'FL', country: 'United States', region: 'americas' },
  { city: 'Toronto', state: 'ON', country: 'Canada', region: 'americas' },
  { city: 'Vancouver', state: 'BC', country: 'Canada', region: 'americas' },
  { city: 'Montreal', state: 'QC', country: 'Canada', region: 'americas' },
  { city: 'London', state: 'England', country: 'United Kingdom', region: 'europe' },
  { city: 'Manchester', state: 'England', country: 'United Kingdom', region: 'europe' },
  { city: 'Berlin', state: 'Berlin', country: 'Germany', region: 'europe' },
  { city: 'Munich', state: 'Bavaria', country: 'Germany', region: 'europe' },
  { city: 'Paris', state: 'Ile-de-France', country: 'France', region: 'europe' },
  { city: 'Amsterdam', state: 'North Holland', country: 'Netherlands', region: 'europe' },
  { city: 'Stockholm', state: 'Stockholm', country: 'Sweden', region: 'europe' },
  { city: 'Sydney', state: 'NSW', country: 'Australia', region: 'asia-pacific' },
  { city: 'Melbourne', state: 'VIC', country: 'Australia', region: 'asia-pacific' },
  { city: 'Singapore', state: 'Singapore', country: 'Singapore', region: 'asia-pacific' },
  { city: 'Tokyo', state: 'Tokyo', country: 'Japan', region: 'asia-pacific' },
  { city: 'Mumbai', state: 'Maharashtra', country: 'India', region: 'asia-pacific' },
];

export const EMAIL_DOMAINS = [
  'gmail.com', 'yahoo.com', 'outlook.com', 'hotmail.com',
  'company.com', 'email.com', 'protonmail.com',
];
