/**
 * Level 7: The Performance Review
 */
export const level7 = {
  id: 'level-7',
  title: 'Performance Review',
  description: 'The final capstone. Prove you have mastered Pandas to earn a promotion.',
  mentor: 'maya',
  icon: '🏆',
  subLevels: [
    // ─── 7.1 The Setup ───────────────────────────────────────────────
    {
      id: '7.1',
      level: 'level-7',
      subLevel: '7.1',
      type: 'guided',
      mentor: 'maya',
      title: 'The Review Meeting',
      subtitle: 'Story time',
      learningObjective: 'Prepare for the capstone challenge.',
      estDuration: '1m',
      datasetCard: {
        filename: 'none',
        rows: '0',
        columns: '0',
        department: 'HR',
        description: 'Meeting agenda.',
        difficulty: 'Beginner'
      },
      summary: {
        concepts: ['Review'],
        why: 'Every Junior Analyst must eventually pass their probation period by demonstrating end-to-end data mastery.',
        next: 'Begin the Capstone Challenge.'
      },
      businessSituation: [
        "Hey. Have a seat.",
        "It's been a few weeks since you started at NovaMetrics.",
        "You've moved through Data Quality, Sales Analytics, Finance, and Logistics.",
        "Today is your probation review. We are going to test everything you've learned."
      ],
      datasets: {},
      starterCode: `# Just hit Run to begin your review.`,
      expectedConcepts: [],
      conversation: {
        situation: [
          "Take a deep breath. Hit Run when you are ready."
        ],
        success: [
          "Alright. Let's see what you've got."
        ],
        hints: [
          "Hit Run."
        ]
      },
      validator: { fn: 'validateDataFrame' } // Can be anything, just a pass-through
    },

    // ─── 7.2 The Capstone Challenge ──────────────────────────────────
    {
      id: '7.2',
      level: 'level-7',
      subLevel: '7.2',
      type: 'challenge',
      mentor: 'maya',
      title: 'The Capstone',
      subtitle: 'End-to-End Analytics',
      learningObjective: 'Independently clean, filter, join, and aggregate a raw database dump.',
      estDuration: '15m',
      datasetCard: {
        filename: 'multiple',
        rows: 'Varies',
        columns: 'Varies',
        department: 'Executive',
        description: 'A raw database dump containing Sales, Customers, and Products.',
        difficulty: 'Expert'
      },
      summary: {
        concepts: ['End-to-End Pipeline'],
        why: 'In the real world, no one gives you a clean dataset. You have to build it yourself.',
        next: 'Receive your performance review results.'
      },
      businessSituation: [
        "The CEO wants a single number: Total revenue generated by 'VIP' customers.",
        "Here are the rules:",
        "1. Load 'customers.csv' and drop anyone missing an email.",
        "2. Load 'orders.csv' and drop duplicates.",
        "3. Inner join orders onto the cleaned customers.",
        "4. A 'VIP' is anyone whose 'loyalty_score' is > 80.",
        "5. Filter the joined table for VIPs only.",
        "6. Calculate the `.sum()` of the 'amount' column.",
        "Assign the final single number (not a dataframe) to `vip_revenue`."
      ],
      datasets: {
        'customers.csv': { generator: 'customers', count: 1000, injections: [{ type: 'missing_values', column: 'email', percentage: 0.1 }] },
        'orders.csv': { generator: 'sales', count: 3000, injections: [{ type: 'duplicates', percentage: 0.1 }] }
      },
      starterCode: `import pandas as pd\n\n# 1. Clean customers\n# 2. Clean orders\n# 3. Join\n# 4. Filter VIPs\n# 5. Sum amount\n\nvip_revenue = `,
      expectedConcepts: ['dropna', 'drop_duplicates', 'merge', 'sum'],
      conversation: {
        situation: [
          "This is entirely up to you. I won't hold your hand.",
          "Read the instructions carefully."
        ],
        success: [
          "...",
          "You actually did it.",
          "The number is exactly correct."
        ],
        hints: [
          "c = pd.read_csv('customers.csv').dropna(subset=['email'])",
          "o = pd.read_csv('orders.csv').drop_duplicates()",
          "j = pd.merge(c, o, on='customer_id', how='inner')",
          "vips = j[j['loyalty_score'] > 80]",
          "vip_revenue = vips['amount'].sum()"
        ]
      },
      validator: { 
        fn: 'validateMultiStage',
        stages: [
          {
            name: "Final Value Type",
            check: "isinstance(vip_revenue, (int, float)) or 'float' in str(type(vip_revenue))",
            feedback: "vip_revenue must be a single number (the sum), not a DataFrame or Series."
          },
          {
            name: "Value Correctness",
            check: "vip_revenue > 0", // We can't know exact number due to random gen, just check it's a valid sum
            feedback: "The sum doesn't look correct. Did you filter for VIPs > 80?"
          }
        ]
      }
    },

    // ─── 7.3 The Promotion ───────────────────────────────────────────
    {
      id: '7.3',
      level: 'level-7',
      subLevel: '7.3',
      type: 'guided',
      mentor: 'maya',
      title: 'The Promotion',
      subtitle: 'Meeting Leo',
      learningObjective: 'Celebrate completing the Pandas curriculum.',
      estDuration: '1m',
      datasetCard: {
        filename: 'none',
        rows: '0',
        columns: '0',
        department: 'HR',
        description: 'Promotion letter.',
        difficulty: 'Beginner'
      },
      summary: {
        concepts: ['Graduation'],
        why: 'You have mastered the foundations of Python Data Analysis.',
        next: 'Prepare for SQL and Data Engineering in the next phase of DataMastery.'
      },
      businessSituation: [
        "Congratulations. You passed.",
        "I'm officially signing off on your probation review. You are now a Mid-Level Data Analyst.",
        "Because of your new title, you're going to be working directly with the data warehouse.",
        "I'd like to introduce you to Leo, our Senior Data Engineer."
      ],
      datasets: {},
      starterCode: `# Congratulations! You have finished the Pandas curriculum.`,
      expectedConcepts: [],
      conversation: {
        situation: [
          "Leo will be taking over your training from here on out.",
          "He's a bit intense, but he knows SQL better than anyone alive."
        ],
        success: [
          "See you around. Good luck with Leo."
        ],
        hints: [
          "Hit Run to finish the curriculum!"
        ]
      },
      validator: { fn: 'validateDataFrame' }
    }
  ]
};
